env: "local"
telegram-bot:
  token: "6799194063:AAGz10mj7MHa4gJwa5zHsoetA8sHCl4B5Cc"
  time-out: 60
postgres:
  host: "localhost"
  port: 5436
  user: "semen"
  password: "semenroot"
  db-name: "test-events"
  ssl-mode: "disable"
redis:
  host: "localhost"
  port: "6379"
  password: "qwerty"
  db-name: 0
